# Generated by Django 4.0.5 on 2022-06-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spodeezer', '0009_alter_musica_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='capa',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
