# Generated by Django 4.0.5 on 2022-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spodeezer', '0010_album_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.CharField(max_length=5),
        ),
    ]
