# Generated by Django 4.0.5 on 2022-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spodeezer', '0011_alter_musica_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='linkmusica',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
